#!/bin/bash

XPI=build.xpi

# List add-on files here.
zip -r $XPI bootstrap.js \
            install.rdf \
            chrome.manifest \
            content \
            skin \
            locale \
            README.md \
    -x *.DS_Store*
